webapp:
  build: application
  volumes:
    - ~/Projects/:/var/www/
  tty: true
nginx:
  build: nginx
  ports:
    - "80:80"
  volumes_from:
    - webapp
  links:
    - php-5.5
    - php-5.6
    - php-7
php-5.5:
  build: php-fpm/5.5
  volumes_from:
    - webapp
  links:
    - db
php-5.6:
  build: php-fpm/5.6
  volumes_from:
    - webapp
  links:
    - db
php-7:
  build: php-fpm/7
  volumes_from:
    - webapp
  links:
    - db
db:
  image: postgres
  environment:
    POSTGRES_DB: "portal"
    POSTGRES_USER: "portal"
    POSTGRES_PASSWORD: "12345678"
  volumes_from:
    - webapp
db2:
  image: mysql
  environment:
    MYSQL_USER: "test"
    MYSQL_DATABASE: "test_db"
    MYSQL_CONTAINER_NAME: "mysql"
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
  volumes_from:
    - webapp