webapp:
  build: application
  volumes:
    - ~/Projects/:/var/www/
  tty: true
nginx:
  build: nginx
  ports:
    - "80:80"
  volumes_from:
    - webapp
  links:
    - php-5.5
    - php-5.6
    - php-7.0
    - php-7.1
php-5.5:
  build: php-fpm/5.5
  volumes_from:
    - webapp
  links:
    - db
php-5.6:
  build: php-fpm/5.6
  volumes_from:
    - webapp
  links:
    - db
php-7.0:
  build: php-fpm/7.0
  volumes_from:
    - webapp
  links:
    - db
php-7.1:
  build: php-fpm/7.1
  volumes_from:
    - webapp
  links:
    - db
db:
  image: postgres
  environment:
    POSTGRES_DB: "your_db"
    POSTGRES_USER: "your_user"
    POSTGRES_PASSWORD: "your_password"
  volumes_from:
    - webapp
db2:
  image: mysql
  environment:
    MYSQL_USER: "your_user"
    MYSQL_DATABASE: "your_db"
    MYSQL_CONTAINER_NAME: "mysql"
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  volumes_from:
    - webapp