webapp:
  build: application
  volumes:
    - ~/Projects/:/var/www/
  tty: true
nginx:
  build: nginx
  ports:
    - "80:80"
  volumes_from:
    - webapp
  links:
    - php-5.5
    - php-5.6
    - php-7
php-5.5:
  build: php-fpm/5.5
  volumes_from:
    - webapp
  links:
    - db
php-5.6:
  build: php-fpm/5.6
  volumes_from:
    - webapp
  links:
    - db
php-7:
  build: php-fpm/7
  volumes_from:
    - webapp
  links:
    - db
db:
  image: postgres
  volumes_from:
    - webapp